name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build NET 7.0
      run: dotnet build --no-restore -c Debug -o build_output/net7 -f net7.0-windows
    - name: Build NETFramework 4.8
      run: dotnet build --no-restore -c Debug -o build_output/netframework48 -f netframework4.8-windows
    - name: Test
      run: dotnet test --no-build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compiled_files
        path: build_output/
  test:
    runs-on: windows-latest
    needs: build
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: compiled_files
        path: build_output/
    - name: Create test files
      run: |
        mkdir test 
        cd test
        for ($i = 1; $i -le 500; $i++) {
          $filename = "test_" + $i + "_pptx"
          New-Item -ItemType File -Path $filename > $null
          $filename = "test_" + $i + "_docx"
          New-Item -ItemType File -Path $filename > $null
          $filename = "test_" + $i + "_xlsx"
          New-Item -ItemType File -Path $filename > $null
        }
        copy test test2
        cd ../ 
        echo all test files set!
    - name: Run NET 7.0 application
      run: |
        Measure-Command {
          build_output/net7/Will_ExtRecover.exe test/ > $nul
          } | Tee-Object -FilePath net7.log
        echo NET 7.0 application finished!
    - name: Run NETFramework 4.8 application
      run: |
        Measure-Command {
          build_output/netframework4.8/Will_ExtRecover.exe test2/ > $nul
          } | Tee-Object -FilePath net4_8.log
        echo NETFramework 4.8 application finished!
    - name: upload logs
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: |
          net7.log
          net4_8.log
